### ISSUE TITLE
Mirth Version Set in 2 Places

### ISSUE THREAD

**Issue by joshmc82** [tonygermano/mirth-user-privacy-plugin#2]
I also filed an issue on the upstream project for a somewhat related bug: https://github.com/kpalang/mirth-sample-plugin/issues/7

The issue here is that you have to remember to set your version in multiple places: `mirth.version` and `plugin.mirthVersion`. In this case, the value is different between the two locations.

The upstream project because appears to not be using the reference specified for `plugin.mirthVersion`. If that gets fixed, can we consider adopting that fix here also?

**Comment by tonygermano** [comment]
They are actually both being used for different purposes.

`mirth.version` specifies the version of mirth that you want to build against. It is referenced in the maven dependencies.

`plugin.mirthVersion` specifies the versions of mirth that you want your plugin to support. It is used in the configuration section for the `mirth-plugin-maven-plugin`.
https://github.com/tonygermano/mirth-user-privacy-plugin/blob/af55ef40ca301e59ee930b7556c755be319ad6b5/distribution/pom.xml#L71-L80

While it's probably good to make them match in general, it is not necessary that they do. In this case, at the time when I created the plugin, the newest version of mirth for which I was creating the plugin had not been uploaded to the maven repo yet, so I used the most recent mirth version that was available to build against. Since the interface I was implementing did not change between versions, it did not matter that the versions did not match.
